### ISSUE TITLE
add support for missing features

### ISSUE THREAD

**Issue by alexfreyre** [Darakah/obsidian-gallery#1]
Hi Darakah, your gallery plugin is amazing. I am a visual artists and I need to have references linked to my notes therefore your plugin is important to me.

The problems I am facing with it:
1. the previews get chopped with the stated **width** but with different **heights**, as a result only portions of each image is "randomly" displayed because in vertical tiles some parts are hidden.
2. right now the only option over the preview tiles is to move them around, a few important options are missing.

ideas for problem 1:
- let the user the option for the **overall height**
- let the user specify the **same value** for both **width and height** 
- let the user the option to set the **scale of the grid** (could be pre-defined options or a float parameter)
- expose **some layouts** and a general scale option:
	1. **square tiles** (this type of grid is which I most need)
	2. **vetical tiles** (with width and height stated before, targeting 1:1, 1:2,4:3, 16:9, or whatever)
	3. **horizontal tiles** (same as above)
	4. **random** (similar to the actual one)

ideas for problem 2:
1. left click shows the *image alone extended to the gallery bounds* and hide the others
2. doble left click:
	- shows the **image in fullscreen** and loop through the gallery list
	- or opens the image with default app 
3. right click shows:
	- **open with default app**
	- **reveal file in navigation** (I often have a bunch of image with random names)
	- **show in system explorer**

Hope these ideas help!

**Comment by Darakah** [comment]
Hello @alexfreyre ,

Glad you liked the plugin. 
Thank you for the detailed feedback and suggestions. Already planning a new version for this plugin (mostly as you suggested different layouts and navigation to location of origin), will try to add some of your requests in that release if possible (most should be easy to add though I need to look how to get obsidian to open a file with an external app and the fullscreen behavior). 

The update will have to wait for a couple of weeks until I have some free time off work.

**Comment by alexfreyre** [comment]
Thanks for the reply, I am new to obsidian and it is very powerful, but I
have some ideas that could help us.

I was thinking that the gallery could link and show videos not only images.
Obsidian itself supports video playback, so it could be done!!!

If you want some feedback regarding any visual feature you want to add to
obsidian you can count with me to help with ideas. (I am not a programmer!)

**Comment by jorgb** [comment]
Hi, 
Wonderful plugin! I would like to add some functionality I would like to see.
- Only scan current folder, on viewable types (right now I see empty renderings assuming these are types Obsidian does not natively render)
- Resolve the clickable note to similar base name for example 2020.030 - Drawing.jpg will open note 2020.030 - Drawing.md with said picture pre-linked if it does not exist, or just open the note if it already exists. 
- Or resolve the image by clicking and opening the image full screen in separate window in Obsidian.
- Support obsidian query for pre-selection of what to show (ties in to scanning notes that have said images in them), but this might get slow.

In any case, it's a very good usable plugin, thank you for making it!

**Comment by Darakah** [comment]
Thank you for your kind words and the nice suggestions!

About to release version `0.5.0`

@jorgb ,
- Added code block filter arguments to filter by path as well as name (both support Regex)

```
type=grid
path=Weekly
name=.*Calen
imgWidth=400
divWidth=70
divAlign=left
reverseOrder=false
customList=5 10 2 4
```
- Added an actual gallery view (now it can be considered an actual gallery ;)
- Can filter images directly by `Path` & `Name`
- Clicking in image focuses on it + `CREATES AN MD NOTE TO LINKED TO IT` in a folder location specified by the user to contain all these image info files. 
- The image file is directly displayed for the clicked image in a panel (in the below image on the right). It can be directly edited by clicking the small `pencil icon` which would switch it to the editor

<img width="1680" alt="Screen Shot 2021-04-09 at 8 38 36 PM" src="https://user-images.githubusercontent.com/29651407/114226189-90873180-9973-11eb-9c29-64fc026c105b.png">

### Clicking the edit button for example:

<img width="1680" alt="Screen Shot 2021-04-09 at 8 42 32 PM" src="https://user-images.githubusercontent.com/29651407/114226635-1dca8600-9974-11eb-878c-4c6e8e2d8893.png">

I can push a later patch to have the files created in the same directory as the image if you need that (I wanted to avoid this as it would clutter the vault for most users - me included ^^ - and having them in 1 folder would make it easier to filter them out in the various searches / graph view). Files are created with a generic name of `Info_##.md` but changing the name doesn't affect anything as long as what is written inside it is not removed (the hidden span which links it to the image). 

-----

@alexfreyre ,
- Added a new view `type=grid` which does not chop off the images ^^ (it is also the view used inside the main gallery)
- You can specify the width in px (not the height, since it is fitting it, it will keep the aspect ratio of the original image and create a properly stacked grid accordingly)
- Clicking on an image inside `type=grid` causes that image to be centered and focused and in its native size (example image above).
- While an image is focused, clicking left / right arrow will allow you to loop through the images while remaining in the focused mode
- Right clicking an image inside a `type=grid` will open the image inside obsidian (original png file). Didn't add the right click options as those can be directly accessed from that note (top right three dots more options) to reveal in finder or open with default app (or if you have hotkeyed the open in default app you can directly use it after right clicking the image). It would be nice to have the options though in the future.

**Comment by jorgb** [comment]
Awesome I am going to be checking this out really soon!
