### ISSUE TITLE
Bug: click doesn't work

### ISSUE THREAD

**Issue by denemier** [Darakah/obsidian-gallery#11]
When i right click on a image on gallery and view the file in programs native file viewer, and then when i comeback with back button on my mouse i can see the gallery but cant click images anymore neither left or right

**Comment by Darakah** [comment]
That is because the event listeners (i.e. click / jump to source) are added by the side panel which if you notice when you use the comeback buttons (it is not the equivalent of opening the tab again) the side panel is not there and thus the clicks will not work. 

Simply click the gallery Ribbon icon when you are back and it should work.

**Comment by Darakah** [comment]
Can make it so that if the gallery is opened from the `comeback` route to create the side panel  thus activating it as normal. Will add it to the next release.

**Comment by Darakah** [comment]
Added in `v0.5.5`.
