### ISSUE TITLE
"Gallery On Path Search" setting won't save

### ISSUE THREAD

**Issue by DaveyUS** [Darakah/obsidian-gallery#12]
- On latest insider build.
- Typing like this - "Files/Footage" (minus quotations)
- Folder is full of .mp4 files
- Clicking save shows no indication of anything happening
- When close and reopening settings, the field is blank again
- Even entering "/" won't save
- Oddly, If I copy and paste the directory location instead of typing it, it will save, but I can't get it to show up in Gallery.
- Tried deleting the Gallery plugin folder and reinstalling from community plugins

**Comment by Darakah** [comment]
@DaveyUS 

Thank you for reporting this. Fixed in `v0.5.8`, it was a change following the latest bug fix. Should work as normal now.
The path that you input in the settings will not show up in the `path` box inside the main gallery but it will be filtered by it (just to keep it clean). 

You can see if the setting has saved by checking the settings tab, the placeholder will refer to the current value for that parameter. 

If the path to that folder does not exist it will not update the parameter, as such make sure it is a valid path.

If this issue persists, feel free to reopen this issue.

**Comment by DaveyUS** [comment]
Looks like that fixed it, although now I'm having a different problem. Not sure if I should open a new one or not, but I'll just say it here.

Only the first .mp4 will show in the gallery. If I add .png images to the folder as a test, those will display fine along with only the first mp4. I have probably 50 mp4s in the folder, all from the same gopro. Let me know if you need my assistance in troubleshooting this!

**Comment by Darakah** [comment]
@DaveyUS 

I can't seem to replicate this, I have a bunch of mp4s in the same folder, they are all displaying fine. Do you get this problem when `path` search is set to `/` ?

**Comment by DaveyUS** [comment]
Yep same problem with `/`. I realized that if I remove the one visible video from the folder, a new .mp4 does _not_ take it's place upon refresh, now there are no videos showing up. If I put the one video back in, it shows up again by itself. These are files straight out of the camera, and all of them can be viewed normally inside of obsidian.

Filtering for `.*mp4$` didn't change anything unfortunately.

**Comment by Darakah** [comment]
Can you create a duplicate of that file that is actually showing up? When you do that, do both of them show up or only one?

If both do show up, it means the problem is with identifying those other videos as proper files. What is there extensions (lower case mp4?), what is different between those and the one showing up?

**Comment by DaveyUS** [comment]
Ah you've figured it out. All of the other files are capital .MP4, which is how they came out of the camera. The working clip was processed with handbrake I think, which is how it ended up lowercase .mp4. Is there a way to support .mp4 in all caps?

**Comment by Darakah** [comment]
Glad it works. Yes, should be simple to fix. Will add it to the next release.

**Comment by OliverJaney** [comment]
hi - im new to Obsidian. I've downloaded and enabled Gallery. but I can't get a path to save (even if I copy in as suggested). Ive uninstalled and reinstalled. I also don't see the gallery icon ton the far right pane as in your demos. please can you assist?
