### ISSUE TITLE
Adding name=* to the config of a gallery results in all files been shown with version 0.5.8

### ISSUE THREAD

**Issue by jaroet** [Darakah/obsidian-gallery#17]
When I have a config like the following ... 

```
```gallery
type=grid
path=.*afbeeldingen/afzwemmen
name=*
```
Then all images found in the vault are shown while I would expect all images in the mentioned folder are shown. 
When I remove the name=* line everything works as expected. 

I am not sure if this is a bug or not (not very familiair with regex) but it was at least note what I was expecting.

**Comment by Darakah** [comment]
Hello,

Thanks for submitting this issue. 

This is not a bug, your regular expression is wrong. it should be `name=.*` instead of `name=*`. Your current regex leads to an error as it would look like `.*afbeeldingen/afzwemmen**`. 

https://github.com/Darakah/obsidian-gallery/blob/334e28de05fef271eacc3c4a51f11fa2443bfe9a/src/utils.ts#L197

Which is caught by the catch block and replaced with `.*` and an error message should be outputed to your obsidian console.

https://github.com/Darakah/obsidian-gallery/blob/334e28de05fef271eacc3c4a51f11fa2443bfe9a/src/utils.ts#L200

**Comment by jaroet** [comment]
OK ... thanks for explaining and sorry for wrongly registring an issue. Seems I have to get some better knowledge of regex then.
